---
version: '3.2'
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:1.10.12-python3.7}
  env_file:
    - .env
  volumes:
    - ./airflow_files/dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./files:/opt/airflow/files
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - airflow

networks:
  airflow:

services:
  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PASSWORD=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./database/data:/var/lib/postgresql/data/pgdata
      - ./database/logs:/var/lib/postgresql/data/log
    command: >
     postgres
       -c listen_addresses=*
       -c logging_collector=on
       -c log_destination=stderr
       -c max_connections=200
    networks:
      - airflow

  redis:
    image: redis:5.0.5
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 6379:6379
    networks:
      - airflow

  webserver:
    <<: *airflow-common
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - postgres
      - redis
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    <<: *airflow-common
    ports:
      - 5555:5555
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - ./logs:/opt/airflow/logs
    command: flower

  scheduler:
    <<: *airflow-common
    command: scheduler
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  worker:
    <<: *airflow-common
    command: worker
    depends_on:
      - scheduler
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  initdb:
    <<: *airflow-common
    entrypoint: /bin/bash
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    command: -c "airflow initdb"
    depends_on:
      - redis
      - postgres
      
